name: Generate Wikidata Thumbnails

on:
  schedule:
    - cron: '0 0 * * *' # Runs every night at midnight (UTC)
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        working-directory: .\wikidata-image-fetcher
        run: dotnet restore
    
      - name: Build the project
        working-directory: .\wikidata-image-fetcher
        run: dotnet build --no-restore --configuration Release
    
      - name: Run the program
        working-directory: .\wikidata-image-fetcher
        run: dotnet run --no-build --configuration Release

      # Step 5: Commit any new files in Foo to the Git repository
      - name: Commit new files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add images\*
          git commit -m "Add new files from nightly run" || echo "No changes to commit"
          git push || echo "No changes to push"